
<p>Ué, não tá conseguindo ver este email? Acesse <a href="http://domiti.la/dhomba" target="_blank">http://domiti.la/dhomba</a>.</p>
<table bgcolor="#e3e667" border="0" cellspacing="0" cellpadding="5" width="600" align="center">
	<tr>
		<td height="160" valign="middle" align="center"><img src="titulo.png" alt="Lançamento do EP1" width="499" height="140" border="0"></td>
	</tr>
	<tr>
		<td><img src="litera.jpg" alt="Banda Lítera" width="600" height="400" border="0"></td>
	</tr>
	<tr>
		<td>

<p>Ah, que coisa mais linda! Que emoção! :)</p>

<p>Depois da turnê por SP e MG chegou a vez de mostrar o novo show e lançar o <strong>EP1 - A Marquesa</strong> em Porto Alegre. Que alegria! :)</p>

<p>Pra comemorar essa data, vamos chamar muitos amigos que fizeram parte dessa trajetória. Pra abrir os trabalhos, abertura de luxo, no caso, a banda que inspira a Lítera em tudo que faz: <strong>a linda e elegante Tarsila</strong>. Dá pra acreditar? </p>

<p>Aí depois vão rolar <strong>participações especiais</strong>, olha só quem já confirmou:</p>

<ul>
<li>Michu - Petit Mort</li>
<li>Iuri Sanson - HIBRIA</li>
<li>Duda Calvin - Tequila Baby</li>
<li>Marcelo Fruet</li>
<li>Átila Viana - Renascentes</li>
<li>Wallau</li>
<li>Beto - Guff</li>
<li>Bruno - Diablo Fuck Show</li>
<li>Lucídio - Tarsila</li>
</ul>

<p>uoouu, meldels!!</p>
		</td>
	</tr>
	<tr>
		<td>

<table cellpadding="0" cellspacing="5">
	<tr valign="top" align="left">
		<th width="150">Quando</th>
		<td width="150">30 de outubro<br>21 horas</td>
		<th>Onde</th>
		<td>Dhomba<br>Lima e Silva, 1037</td>
	</tr>
	<tr valign="top" align="left">
		<th>Ingresso</th>
		<td>15 reais na lista<br>20 reais na hora</td>
		<th>Abertura</th>
		<td>Tarsila<br><a href="http://lugardatarsila.com.br" target="_blank">lugardatarsila.com.br</a></td>
	</tr>
	<tr>
		<th>Nome na lista</th>
		<td colspan="3"><a href="http://dhomba.tempsite.ws/new/agenda/item/663" target="_blank">dhomba.com.br</a></td>
	</tr>
</table>

		</td>
	</tr>
	<tr>
		<td>
<p>Então, seguinte... mais que um show de lançamento, <strong>vai ser uma grande festa</strong>!</p>

<table cellpadding="0" cellspacing="5">
	<tr>
		<td><img src="disco.jpg" alt="Capa do disco" width="200" height="200" border="0"></td>
		<td valign="top">
<p>O ingresso é ridículo, olha só isso, tu paga <strong>15 pila</strong> com o nome na lista e <strong>ganha o cd A Marquesa</strong>!</p>
<p>FALA SÉRIO! Que coisa linda!</p>
<p>Ou compra na hora o ingresso e paga 20 pila e leva o EP também.</p>
<p>Pára, muito tri isso!</p>
		</td>
	</tr>
</table>

<p>Então nada de preguiça, sai um pouco da internet e vai lá <strong>dia 30</strong> dar um abraço na gente, cantar, dançar e zaz! o/</p>

		</td>
	</tr>
	<tr>
		<td><a target="_blank" href="http://domiti.la/" title="Ouça, baixe e leie as letras das músicas. Veja as informações do próximo show e ingressos"><img src="site.png" alt="Hotsite domiti.la" width="523" height="84" border="0"></a></td>
	</tr>
	<tr>
		<td><img src="domitila.jpg" alt="Domitila aguardando voces lá" width="600" height="400" border="0"></td>
	</tr>
</table>
